# Generated by Django 2.0.6 on 2018-10-16 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('weight', models.FloatField()),
                ('magic', models.BooleanField()),
                ('capacity', models.FloatField(null=True)),
                ('uses', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortableHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('contents', models.TextField(default='{}')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('base_currency', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fields', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pocketdimension.Item')),
            ],
            bases=('pocketdimension.item',),
        ),
        migrations.AddField(
            model_name='portablehole',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.System'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.System'),
        ),
        migrations.AddField(
            model_name='category',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.System'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.Type'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='portablehole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocketdimension.PortableHole'),
        ),
    ]
