# Generated by Django 2.1.5 on 2019-01-25 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pocket_dimension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portablehole',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portablehole',
            name='party_members',
            field=models.ManyToManyField(related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portablehole',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.System'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.System'),
        ),
        migrations.AddField(
            model_name='category',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.System'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.Type'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='portable_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket_dimension.PortableHole'),
        ),
    ]
